name: armulator
services:
  emulator:
    container_name: "armulator"
    build:
      context: ./Emu
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
      - "8001:443"
    environment:
      METADATA_SERVER: azurite
      AzureStorage.IsHeadless: false
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_HTTPS_PORTS: 8001
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - azurite
    networks:
      arm-emulator:
        aliases:
          - "arm-emulator"
  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      arm-emulator:
        aliases:
          - "azurite"
networks:
  arm-emulator: